# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.144.3+26.1

# Mod Properties
	mod_version = 4.3.0+26.1
	maven_group = com.jummit
	archives_base_name = nethermap

# Dependencies
	modmenu_version=18.0.0-alpha.8
	clothconfig_version=26.1.154
	polymer_version=0.16.0-pre.3+26.1
